### ISSUE TITLE
DIN Lookalike: Data Sampling understanding

### ISSUE THREAD

**Issue by SatyamSwarup** [apache/incubator-bluemarlin#28]
Hello Jimmy, 

We would like to understand how you did sampling in the lookalike_build_dataset.py script.

![image](https://user-images.githubusercontent.com/51720850/149085830-1a5398ab-b943-41a1-9450-11eb1e3f9561.png)

It would be great if you can share an informal description of this sampling method, so that we can reproduce it at our end.

Thanks.

**Comment by jimmylao** [comment]
Please find the attach pdf file for an illustration of sample extraction process used.
[sample-extraction-example.pdf](https://github.com/apache/incubator-bluemarlin/files/7855939/sample-extraction-example.pdf)

**Comment by sanjaynirmal** [comment]
@jimmylao 
Thanks for the document, Can we have a session on the understanding of this pdf that you have shared above. 
It would be better if we can have a separate session for this today, some hours before the scheduled weekly meeting as per your convenience.
